version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install -r requirements_dev.txt
            pip install coverage
            pip install pytest

      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run -m pytest

      - restore_cache:
          name: Restore Yarn Package Cache
          key: nvm-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum ".circleci/nvm_env.sh" }}
      - run:
          command: |
            wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh -O nvm.sh
            chmod +x nvm.sh
            ./nvm.sh
      - run:
          command: |
            source .circleci/nvm_env.sh
            nvm install 12
            nvm alias default node
            npm install -g yarn
      - save_cache:
          key: nvm-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum ".circleci/nvm_env.sh" }}
          paths:
            - '~/.nvm'

      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "~/repo/py_type_extractor/plugins/typescript/yarn.lock" }}
      - run:
          command: |
            source .circleci/nvm_env.sh
            cd ~/repo/py_type_extractor/plugins/typescript
            yarn
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "~/repo/py_type_extractor/plugins/typescript/yarn.lock" }}
          paths:
              - '~/repo/py_type_extractor/plugins/typescript/node_modules'
      - run:
          command: |
            source venv/bin/activate
            source .circleci/nvm_env.sh
            cd ~/repo/py_type_extractor/plugins/typescript
            yarn run test

      # store artifacts (for example logs, binaries, etc)
      # to be available in the web app or through the API
      - store_artifacts:
          path: test-reports

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9